### ISSUE TITLE
Launcher spikes to high CPU after running for a while (approx. an hour)

### ISSUE THREAD

**Issue by GinjaNinja32** [Slowpoke101/FTBLaunch#960] opened 2015-11-08 02:57 UTC
I'm running launcher version 1.4.10, FTB Infinity 1.11.2, Java 8u60 on Linux. Restarting the launcher fixes it temporarily, but it comes back after around an hour of playing.

Once it starts spiking, it gets worse over time, eventually freezing Minecraft every couple of seconds by taking up the entirety of the available CPU time:
![](http://nyx.gn32.uk/i/2015-11-08_02:55:35.png)
(the 9 'running' tasks are htop and 8 FTB launcher threads)

**Comment by jikuja** [comment] 2015-11-08 03:01
Try closing console window.

**Comment by GinjaNinja32** [comment] 2015-11-08 03:09
This is with the console window disabled.

**Comment by jikuja** [comment] 2015-11-10 19:03
Interesting. What if you start it with `java -jar FTB_Launcher.jar --disable-mc-logging` 

If that high CPU usage is caused by something else than logging then you have found a new bug.

**Comment by GinjaNinja32** [comment] 2015-11-11 00:08
With `--disable-mc-logging` it doesn't spike.

What's going on in logging that it needs that much power?

**Comment by nallar** [comment] 2016-01-22 17:34
Sorry about the "added a commit" spam which showed up on this issue. Didn't realise github would add a separate link every time I rebased without removing the old ones.

**Closed** 2016-04-15 23:56 UTC
